// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAI.Infrastructure.Persistence;

#nullable disable

namespace SAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119212945_AddedAttributes")]
    partial class AddedAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SearchAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac7c941c-f5f3-466e-ad15-a0b97778a576"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(75),
                            Key = "City"
                        },
                        new
                        {
                            Id = new Guid("ed33906d-67f1-4ae3-8990-9a14315cbbb7"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(99),
                            Key = "Brand"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SearchAttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("SearchAttributeId");

                    b.ToTable("SearchAttributeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("103d7ed1-7474-4df1-a963-8a220d068a8b"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(283),
                            SearchAttributeId = new Guid("ac7c941c-f5f3-466e-ad15-a0b97778a576"),
                            Value = "Baku"
                        },
                        new
                        {
                            Id = new Guid("f0b18540-8e31-455e-8a81-238fb60b09ca"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(316),
                            SearchAttributeId = new Guid("ac7c941c-f5f3-466e-ad15-a0b97778a576"),
                            Value = "Ganja"
                        },
                        new
                        {
                            Id = new Guid("7b48a2b1-99ff-46f3-ba87-88ecd42cd0d7"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(344),
                            SearchAttributeId = new Guid("ed33906d-67f1-4ae3-8990-9a14315cbbb7"),
                            Value = "Apple"
                        },
                        new
                        {
                            Id = new Guid("b0af7090-d7d9-4529-91b0-e9e54b00c86c"),
                            CreatedAt = new DateTime(2026, 1, 19, 21, 29, 44, 858, DateTimeKind.Utc).AddTicks(378),
                            SearchAttributeId = new Guid("ed33906d-67f1-4ae3-8990-9a14315cbbb7"),
                            Value = "Samsung"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.HasOne("SAI.Core.Entities.SearchAttribute", "SearchAttribute")
                        .WithMany("Options")
                        .HasForeignKey("SearchAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchAttribute");
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
