// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAI.Infrastructure.Persistence;

#nullable disable

namespace SAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121210242_Updated Optons table")]
    partial class UpdatedOptonstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SearchAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90caf9da-f098-4993-a699-e239e8981d1b"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3163),
                            Key = "City"
                        },
                        new
                        {
                            Id = new Guid("92cd3861-57dc-435f-a561-69360bf86ad0"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3187),
                            Key = "Brand"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SearchAttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ValueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("SearchAttributeId");

                    b.ToTable("SearchAttributeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("088cfeb6-9372-4fce-93c7-5f596e6b5760"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3368),
                            SearchAttributeId = new Guid("90caf9da-f098-4993-a699-e239e8981d1b"),
                            Value = "Baku",
                            ValueId = "uydbajs"
                        },
                        new
                        {
                            Id = new Guid("c3ccc437-f273-49d7-bf50-6e420ac20b0b"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3396),
                            SearchAttributeId = new Guid("90caf9da-f098-4993-a699-e239e8981d1b"),
                            Value = "Ganja",
                            ValueId = "123"
                        },
                        new
                        {
                            Id = new Guid("b896e7e1-a73a-4e94-ba54-71a06d3376c1"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3429),
                            SearchAttributeId = new Guid("92cd3861-57dc-435f-a561-69360bf86ad0"),
                            Value = "Apple",
                            ValueId = "090"
                        },
                        new
                        {
                            Id = new Guid("65ee8b90-183b-49bb-a7d4-18f8362cd22c"),
                            CreatedAt = new DateTime(2026, 1, 21, 21, 2, 42, 303, DateTimeKind.Utc).AddTicks(3458),
                            SearchAttributeId = new Guid("92cd3861-57dc-435f-a561-69360bf86ad0"),
                            Value = "Samsung",
                            ValueId = "123"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.HasOne("SAI.Core.Entities.SearchAttribute", "SearchAttribute")
                        .WithMany("Options")
                        .HasForeignKey("SearchAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchAttribute");
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
