// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAI.Infrastructure.Persistence;

#nullable disable

namespace SAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SearchAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd111c0-e8cb-4df4-8ddc-1ee168701df4"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7568),
                            Key = "City"
                        },
                        new
                        {
                            Id = new Guid("3591b6a0-2569-4572-885c-8e6ef5358a48"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7587),
                            Key = "Brand"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SearchAttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ValueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("SearchAttributeId");

                    b.ToTable("SearchAttributeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("23e2be53-c37e-4be3-bccb-ffde84c9597a"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7768),
                            SearchAttributeId = new Guid("bbd111c0-e8cb-4df4-8ddc-1ee168701df4"),
                            Value = "Baku",
                            ValueId = "uydbajs"
                        },
                        new
                        {
                            Id = new Guid("72c1eeb9-c1df-44ec-9269-9637513b2056"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7796),
                            SearchAttributeId = new Guid("bbd111c0-e8cb-4df4-8ddc-1ee168701df4"),
                            Value = "Ganja",
                            ValueId = "123"
                        },
                        new
                        {
                            Id = new Guid("42ad5237-2f46-4b42-afa9-b6cac00008ed"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7829),
                            SearchAttributeId = new Guid("3591b6a0-2569-4572-885c-8e6ef5358a48"),
                            Value = "Apple",
                            ValueId = "090"
                        },
                        new
                        {
                            Id = new Guid("c938abd4-f7e1-4355-81bb-31e361f8b5d6"),
                            CreatedAt = new DateTime(2026, 1, 22, 12, 22, 34, 258, DateTimeKind.Utc).AddTicks(7857),
                            SearchAttributeId = new Guid("3591b6a0-2569-4572-885c-8e6ef5358a48"),
                            Value = "Samsung",
                            ValueId = "123"
                        });
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttributeOption", b =>
                {
                    b.HasOne("SAI.Core.Entities.SearchAttribute", "SearchAttribute")
                        .WithMany("Options")
                        .HasForeignKey("SearchAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchAttribute");
                });

            modelBuilder.Entity("SAI.Core.Entities.SearchAttribute", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
